### ISSUE TITLE
Failed to activate the minimap-autohider package

### ISSUE THREAD

**Issue by kinghat** [ansballard/minimap-autohider#6]
[Enter steps to reproduce:]

1. ... applied 1.5.2
2. ... restarted atom at the request. error happened on atom load.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap-autohider](https://github.com/ansballard/minimap-autohider) package 1.5.2

### Stack Trace

Failed to activate the minimap-autohider package

```
At Cannot read property 'addEventListener' of undefined

TypeError: Cannot read property 'addEventListener' of undefined
    at minimapsSubscription.minimap.observeMinimaps.minimap (/packages/minimap-autohider/lib/minimap-autohider.js:40:20)
    at editorsMinimaps.forEach (/packages/minimap/lib/main.js:377:51)
    at Map.forEach (native)
    at Main.observeMinimaps (/packages/minimap/lib/main.js:377:28)
    at Object.activatePlugin (/packages/minimap-autohider/lib/minimap-autohider.js:30:53)
    at Main.activatePlugin (/packages/minimap/lib/mixins/plugin-management.js:187:12)
    at Main.updatesPluginActivationState (/packages/minimap/lib/mixins/plugin-management.js:171:14)
    at /packages/minimap/lib/mixins/plugin-management.js:241:12)
    at Config.module.exports.Config.observeKeyPath (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:625:13)
    at Config.module.exports.Config.observe (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:150:27)
    at Main.registerPluginControls (/packages/minimap/lib/mixins/plugin-management.js:240:53)
    at Main.registerPlugin (/packages/minimap/lib/mixins/plugin-management.js:83:12)
    at Object.consumeMinimapServiceV1 (/packages/minimap-autohider/lib/minimap-autohider.js:19:25)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:846:34
```

### Commands

```
     -0:30.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-python-run 0.7.3 
atom-runner 2.7.1 
autocomplete-python 1.8.64 
comment 0.6.1 
copy-on-select 0.2.0 
file-icons 2.1.7 
highlight-selected 0.13.1 
hyperclick 0.0.40 
minimap 4.28.2 
minimap-autohider 1.5.2 
one-dark-material-syntax 1.0.3 
quick-highlight 0.10.0 
script 3.15.0 
```

also happening on every start of atom now.

**Comment by ansballard** [comment]
Should be resolved, let me know if otherwise!

**Comment by kinghat** [comment]
no more error. ty
